{
add = lambda(x ..) 
    {
    n=len(x); 
    sum=lambda(s,i) 
        if i>=n: 
            s: 
            sum(s+x[i],i+1); 
    sum(0,0)
    }
;
def mapref(L,n) =  
    {
    loop=lambda(i,s) 
        if i<0 :
            s :
            loop(i-1, s+[L[i][n]]);
    loop(len(L)-1,[])
    }
;
map = lambda(f,L ..) 
    if len(L)==1:
        {
        loop=lambda(s,i) 
            if i<0:
                s:
                loop([f(L[0][i])]+s,i-1);
        loop([],len(L[0])-1)
        }: 
    {
    loop=lambda(s,i) 
        if i<0 :
            s :
            loop([apply(f,mapref(L,i))]+s,i-1);
    loop([],len(L)-1)
    }
; 
range = lambda(l ..) 
    {
    s=0;
    e=0;
    stp=1;
    n=len(l);
    if n==1:
        e=l[0]:
    if n==2:
        {
        s=l[0];
        e=l[1]
        }:
    if n==3:
        {
        s=l[0];
        e=l[1];
        stp=l[3]
        }:
        [];
    (loop=lambda(i,r) if i>=e:r:loop(i+stp,r+[i]))(s,[])
    }
; 
tarai=lambda(x,y,z) if x<=y: y : {zz=z();tarai(tarai(x-1,y,lambda() zz),tarai(y-1,zz,lambda() x),lambda() tarai(zz-1,x,lambda() y))}
}
